using System.Threading;
using System.Threading.Tasks;

namespace Automaticks.Diagnostics.CodeAnalysis.Analyzers.Tests;

/// <summary>
///     Tests for GeneratedCodeMarkerAnalyzer.
/// </summary>
public class GeneratedCodeMarkerAnalyzerTests
{
    private const string MarkedSource = """
                                        // <auto-generated/>
                                        namespace MyApp {
                                            public class Foo {}
                                        }
                                        """;
    private const string PlainSource = """
                                       namespace MyApp {
                                           public class Foo {}
                                       }
                                       """;

    /// <summary>
    ///     Tests that Analyze_AutoGeneratedHeaderInSourceFile_ReportsDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_AutoGeneratedHeaderInSourceFile_ReportsDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Foo.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, MarkedSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsTrue();
    }

    /// <summary>
    ///     Tests that Analyze_AutoGeneratedHeaderUnderBin_ReportsNoDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_AutoGeneratedHeaderUnderBin_ReportsNoDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\bin\\Debug\\Foo.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, MarkedSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsFalse();
    }

    /// <summary>
    ///     Tests that Analyze_AutoGeneratedHeaderUnderObj_ReportsNoDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_AutoGeneratedHeaderUnderObj_ReportsNoDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\obj\\Debug\\Foo.GlobalUsings.g.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, MarkedSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsFalse();
    }

    /// <summary>
    ///     Tests that Analyze_CompactAutoGeneratedHeader_ReportsDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_CompactAutoGeneratedHeader_ReportsDiagnostic(CancellationToken cancellationToken)
    {
        const string source = """
                              /* <autogenerated> tooling output </autogenerated> */
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Foo.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, source, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsTrue();
    }

    /// <summary>
    ///     Tests that Analyze_DesignerFileName_ReportsNoDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_DesignerFileName_ReportsNoDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Resources.Designer.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, MarkedSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsFalse();
    }

    /// <summary>
    ///     Tests that Analyze_GeneratedFileNameWithoutDirectory_ReportsDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_GeneratedFileNameWithoutDirectory_ReportsDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "Widget.generated.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, PlainSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsTrue();
    }

    /// <summary>
    ///     Tests that Analyze_GeneratedSuffixFileName_ReportsDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_GeneratedSuffixFileName_ReportsDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Widget.g.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, PlainSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsTrue();
    }

    /// <summary>
    ///     Tests that Analyze_InterchangeGeneratedSuffixFileName_ReportsDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_InterchangeGeneratedSuffixFileName_ReportsDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Widget.g.i.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, PlainSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsTrue();
    }

    /// <summary>
    ///     Tests that Analyze_OrdinaryCommentInSourceFile_ReportsNoDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_OrdinaryCommentInSourceFile_ReportsNoDiagnostic(CancellationToken cancellationToken)
    {
        const string source = """
                              // Ordinary header comment.
                              /* block comment */
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Foo.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, source, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsFalse();
    }

    /// <summary>
    ///     Tests that Analyze_PlainSourceFile_ReportsNoDiagnostic.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Analyze_PlainSourceFile_ReportsNoDiagnostic(CancellationToken cancellationToken)
    {
        var options = new AnalysisOptions
        {
            FilePath = "C:\\repo\\src\\Foo.cs"
        };

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var diagnostics = await AnalyzerTestRunner.AnalyzeAsync(analyzer, PlainSource, options, cancellationToken);

        await Assert.That(DiagnosticCollectionAssertions.HasId(diagnostics, "ATXDC021")).IsFalse();
    }
}
