using Automaticks.Diagnostics.CodeAnalysis;
using Automaticks.Diagnostics.CodeAnalysis.CodeFixes;
using System.Threading;
using System.Threading.Tasks;

namespace Automaticks.Diagnostics.CodeAnalysis.Analyzers.Tests;

/// <summary>Tests for GeneratedCodeMarkerCodeFixProvider.</summary>
public class GeneratedCodeMarkerCodeFixProviderTests
{
    /// <summary>Verifies every marker comment is cleared when the fix is applied repeatedly.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ApplyAllFixes_AutoGeneratedHeader_ClearsMarker(CancellationToken cancellationToken)
    {
        const string source = """
                              // <auto-generated/>
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            Provider = provider,
            Source = source
        };
        var fixedSource = await CodeFixTestRunner.ApplyAllFixesAsync(request, cancellationToken);

        await Assert.That(fixedSource).DoesNotContain("auto-generated");
    }

    /// <summary>Verifies the marker comment is deleted and the declaration is kept.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ApplyFix_AutoGeneratedHeader_RemovesMarker(CancellationToken cancellationToken)
    {
        const string source = """
                              // <auto-generated/>
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            Provider = provider,
            Source = source
        };
        var fixedSource = await CodeFixTestRunner.ApplyFixAsync(request, cancellationToken);

        await Assert.That(fixedSource).DoesNotContain("auto-generated");
        await Assert.That(fixedSource).Contains("public class Foo {}");
    }

    /// <summary>Verifies a marker written as a block comment is deleted.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ApplyFix_BlockCommentMarker_RemovesMarker(CancellationToken cancellationToken)
    {
        const string source = """
                              /* <auto-generated> tooling </auto-generated> */
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            Provider = provider,
            Source = source
        };
        var fixedSource = await CodeFixTestRunner.ApplyFixAsync(request, cancellationToken);

        await Assert.That(fixedSource).DoesNotContain("auto-generated");
    }

    /// <summary>Verifies an indented marker is deleted along with its leading whitespace.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ApplyFix_IndentedMarker_RemovesMarker(CancellationToken cancellationToken)
    {
        const string source = """
                                  // <auto-generated/>
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            Provider = provider,
            Source = source
        };
        var fixedSource = await CodeFixTestRunner.ApplyFixAsync(request, cancellationToken);

        await Assert.That(fixedSource).DoesNotContain("auto-generated");
    }

    /// <summary>Verifies unrelated leading comments are preserved when the marker is deleted.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ApplyFix_MarkerAfterOtherComment_KeepsOtherComment(CancellationToken cancellationToken)
    {
        const string source = """
                              // Copyright header.
                              // <auto-generated/>
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            Provider = provider,
            Source = source
        };
        var fixedSource = await CodeFixTestRunner.ApplyFixAsync(request, cancellationToken);

        await Assert.That(fixedSource).DoesNotContain("auto-generated");
        await Assert.That(fixedSource).Contains("// Copyright header.");
    }

    /// <summary>Verifies a marker on the final line with no trailing newline is deleted.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ApplyFix_MarkerWithoutTrailingNewLine_RemovesMarker(CancellationToken cancellationToken)
    {
        const string source = "// <auto-generated/>";

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            Provider = provider,
            Source = source
        };
        var fixedSource = await CodeFixTestRunner.ApplyFixAsync(request, cancellationToken);

        await Assert.That(fixedSource).DoesNotContain("auto-generated");
    }

    /// <summary>Verifies no fix is offered when the marker is the file name, which renaming alone can resolve.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task CountRegisteredActions_GeneratedFileName_OffersNoFix(CancellationToken cancellationToken)
    {
        const string source = """
                              namespace MyApp {
                                  public class Foo {}
                              }
                              """;

        var analyzer = new GeneratedCodeMarkerAnalyzer();
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var request = new CodeFixRequest
        {
            Analyzer = analyzer,
            DocumentName = "Widget.g.cs",
            Provider = provider,
            Source = source
        };
        var offered = await CodeFixTestRunner.CountRegisteredActionsAsync(request, cancellationToken);

        await Assert.That(offered).IsEqualTo(0);
    }

    /// <summary>Verifies GetFixAllProvider returns the batch fixer.</summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task GetFixAllProvider_Called_ReturnsBatchFixer(CancellationToken cancellationToken)
    {
        var provider = new GeneratedCodeMarkerCodeFixProvider();
        var fixAllProvider = provider.GetFixAllProvider();

        await Assert.That(fixAllProvider).IsNotNull();
    }
}
