using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;

namespace Automaticks.Diagnostics.CodeAnalysis;

/// <summary>
///     Flags a generated-code marker on a hand-written source file.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class GeneratedCodeMarkerAnalyzer : DiagnosticAnalyzer
{
    private const string AutoGeneratedMarker = "<auto-generated";
    private const string AutoGeneratedMarkerCompact = "<autogenerated";
    private static readonly DiagnosticDescriptor Rule;

    static GeneratedCodeMarkerAnalyzer()
    {
        var rule = new DiagnosticDescriptor(
            DiagnosticIds.DiagnosticsCodeAnalysis.GeneratedCodeMarker,
            "Generated-code marker is not allowed in hand-written source",
            "'{0}' is marked as generated code, which exempts it from every analyzer. Remove the marker and fix what it hides. A code fix is available (dotnet format analyzers --diagnostics ATXDC021).",
            "Diagnostics.CodeAnalysis",
            DiagnosticSeverity.Error,
            true,
            "Remove the `<auto-generated>` header, or rename the file so it does not end in `.g.cs`, `.generated.cs` or `.g.i.cs`. Roslyn skips generated files for every rule in this suite, so the marker is a blanket suppression with no reviewable trace. Real build output under `obj` or `bin`, and checked-in `.designer.cs` files, are exempt.");
        Rule = rule;
    }

    /// <inheritdoc />
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics);
        context.EnableConcurrentExecution();
        context.RegisterSyntaxTreeAction(AnalyzeSyntaxTree);
    }

    /// <inheritdoc />
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

    private void AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context)
    {
        var path = context.Tree.FilePath;

        if (HasBuildOutputPath(path) || HasDesignerFileName(path))
        {
            return;
        }

        if (HasGeneratedFileName(path))
        {
            var span = new TextSpan(0, 0);
            var start = Location.Create(context.Tree, span);
            context.ReportDiagnostic(Diagnostic.Create(Rule, start, GetFileName(path)));
            return;
        }

        var marker = GetAutoGeneratedMarkerTrivia(context);

        if (marker is { } trivia)
        {
            context.ReportDiagnostic(Diagnostic.Create(Rule, trivia.GetLocation(), GetFileName(path)));
        }
    }

    private SyntaxTrivia? GetAutoGeneratedMarkerTrivia(SyntaxTreeAnalysisContext context)
    {
        var root = context.Tree.GetRoot(context.CancellationToken);

        foreach (var trivia in root.GetLeadingTrivia())
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) && !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                continue;
            }

            var text = trivia.ToString();

            if (text.IndexOf(AutoGeneratedMarker, StringComparison.Ordinal) >= 0
                || text.IndexOf(AutoGeneratedMarkerCompact, StringComparison.Ordinal) >= 0)
            {
                return trivia;
            }
        }

        return null;
    }

    private string GetFileName(string path)
    {
        var separator = path.LastIndexOfAny(['\\', '/']);
        return separator < 0 ? path : path.Substring(separator + 1);
    }

    private bool HasBuildOutputPath(string path)
    {
        var normalized = path.Replace('\\', '/');
        return normalized.IndexOf("/obj/", StringComparison.OrdinalIgnoreCase) >= 0
            || normalized.IndexOf("/bin/", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    private bool HasDesignerFileName(string path)
    {
        return path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private bool HasGeneratedFileName(string path)
    {
        return path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase);
    }
}
